# Top-level Bazel build for multiblend

package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # GPLv3 in repo; see gpl-3.0.txt

cc_binary(
    name = "multiblend",
    srcs = [
        "src/multiblend.cpp",
    ],
    deps = [
        ":m_inc",
    ],
    copts = [
        "-msse4.1",
        "-pthread",
        "-ffast-math",
        "-Ofast",
    ],
    linkopts = [
        "-lm",
        "-lpng",
        "-ltiff",
        "-ljpeg",
        "-pthread",
    ],
)


cc_library(
    name = "m_inc",
    srcs = [],
    hdrs = [
        "src/pnger.cpp",
        "src/pyramid.cpp",
        "src/pyramid.h",
        "src/threadpool.h",
        "src/threadpool.cpp",
        "src/mapalloc.cpp",
        "src/mapalloc.h",
        "src/geotiff.cpp",
        "src/image.cpp",
        "src/functions.cpp",
    ],
    includes = [
        "src",
    ],
)

py_binary(
    name = "install",
    srcs = ["tools/install.py"],
    data = [":multiblend"],
    args = ["--binary=$(location :multiblend)"],
)
