cc_test(
    name = "mapalloc_test",
    size = "small",
    srcs = ["mapalloc_test.cc"],
    deps = [
        "//:mapalloc_lib",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "mapalloc_edge_test",
    size = "small",
    srcs = ["mapalloc_edge_test.cc"],
    deps = [
        "//:mapalloc_lib",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "threadpool_test",
    size = "small",
    srcs = ["threadpool_test.cc"],
    deps = [
        "//:threadpool_lib",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "pnger_test",
    size = "small",
    srcs = ["pnger_test.cc"],
    deps = [
        "//:pnger_lib",
        "@com_google_googletest//:gtest_main",
    ],
    linkopts = ["-lpng", "-lm"],
)

cc_test(
    name = "image_open_test",
    size = "small",
    srcs = ["image_open_test.cc"],
  deps = [
      "//:image_lib",
      "@com_google_googletest//:gtest_main",
  ],
  linkopts = ["-lpng", "-ltiff", "-ljpeg", "-lm", "-pthread"],
)

cc_test(
    name = "jpeg_open_test",
    size = "small",
    srcs = ["jpeg_open_test.cc"],
    deps = [
        "//:image_lib",
        "@com_google_googletest//:gtest_main",
    ],
    linkopts = ["-lpng", "-ltiff", "-ljpeg", "-lm", "-pthread"],
)

cc_test(
    name = "geotiff_open_test",
    size = "small",
    srcs = ["geotiff_open_test.cc"],
    deps = [
        "//:image_lib",
        "@com_google_googletest//:gtest_main",
    ],
    linkopts = ["-lpng", "-ltiff", "-ljpeg", "-lm", "-pthread"],
)

cc_test(
    name = "tiff_alpha_mask_test",
    size = "small",
    srcs = ["tiff_alpha_mask_test.cc"],
    deps = [
        "//:image_lib",
        "@com_google_googletest//:gtest_main",
    ],
    linkopts = ["-lpng", "-ltiff", "-ljpeg", "-lm", "-pthread"],
)
